const $=id=>document.getElementById(id);let adminCats=[],adminProducts=[];
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2600)}
function requireDb(){if(!db){toast('Configure SUPABASE_URL e SUPABASE_ANON_KEY em js/supabase.js');return false}return true}
async function checkSession(){if(!requireDb())return;const {data}=await db.auth.getSession();if(data.session)showPanel();}
$('loginBtn').onclick=async()=>{if(!requireDb())return;const {error}=await db.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)return toast(error.message);showPanel()}
$('logoutBtn').onclick=async()=>{await db.auth.signOut();$('panel').style.display='none';$('loginBox').style.display='block'}
async function showPanel(){$('loginBox').style.display='none';$('panel').style.display='block';await loadAdminData()}
async function loadAdminData(){const [{data:cats},{data:prods,error}]=await Promise.all([db.from('categories').select('*').order('name'),db.from('products').select('*').order('created_at',{ascending:false})]);adminCats=cats||[];adminProducts=prods||[];$('category_id').innerHTML=adminCats.map(c=>`<option value="${c.id}">${c.name}</option>`).join('');$('adminCount').textContent=`${adminProducts.length} produto(s) no inventário`;if(error)toast(error.message);renderRows()}
function renderRows(){$('productRows').innerHTML=adminProducts.map(p=>`<tr><td>${p.name}<br><small>${p.slug||''}</small></td><td>${money(p.price)}</td><td>${p.is_active?'Ativo':'Inativo'}</td><td><button class="btn btn-ghost" onclick="editProduct('${p.id}')">Editar</button> <button class="btn btn-ghost" onclick="deleteProduct('${p.id}')">Excluir</button></td></tr>`).join('')}
window.editProduct=id=>{const p=adminProducts.find(x=>x.id===id);Object.keys(p).forEach(k=>{if($(k)){if($(k).type==='checkbox')$(k).checked=!!p[k];else $(k).value=Array.isArray(p[k])?p[k].join(', '):(typeof p[k]==='object'?JSON.stringify(p[k]):p[k]??'')}});$('productId').value=p.id;scrollTo({top:0,behavior:'smooth'})}
window.deleteProduct=async id=>{if(!confirm('Excluir este item?'))return;const {error}=await db.from('products').delete().eq('id',id);if(error)return toast(error.message);toast('Produto excluído');loadAdminData()}
$('resetBtn').onclick=()=>document.querySelectorAll('#panel input,#panel textarea').forEach(i=>{if(i.type==='checkbox')i.checked=i.id==='is_active'||i.id==='is_customizable';else i.value=''})
$('saveBtn').onclick=async()=>{if(!requireDb())return;let gallery=[];try{gallery=$('gallery').value.trim().startsWith('[')?JSON.parse($('gallery').value):$('gallery').value.split(',').map(x=>x.trim()).filter(Boolean)}catch(e){return toast('Galeria inválida')}const payload={name:$('name').value,slug:$('slug').value,price:Number($('price').value||0)||null,image_url:$('image_url').value,gallery,shopee_url:$('shopee_url').value,category_id:$('category_id').value,rarity:$('rarity').value,item_type:$('item_type').value,material:$('material').value,stock:Number($('stock').value||0),delivery_note:$('delivery_note').value,tags:$('tags').value.split(',').map(t=>t.trim()).filter(Boolean),featured_rank:Number($('featured_rank').value||0),short_description:$('short_description').value,description:$('description').value,is_active:$('is_active').checked,is_featured:$('is_featured').checked,is_legendary:$('is_legendary').checked,is_customizable:$('is_customizable').checked,is_made_to_order:$('is_made_to_order').checked,has_shopee:!!$('shopee_url').value};const id=$('productId').value;const {error}=id?await db.from('products').update(payload).eq('id',id):await db.from('products').insert(payload);if(error)return toast(error.message);toast('Produto salvo');loadAdminData()}
$('saveCatBtn').onclick=async()=>{if(!requireDb())return;const {error}=await db.from('categories').insert({name:$('catName').value,slug:$('catSlug').value,icon:$('catIcon').value,is_active:true});if(error)return toast(error.message);toast('Categoria salva');loadAdminData()}
checkSession();
