const categoriesFallback = [
  {id:'canecas',name:'Canecas',slug:'canecas',icon:'☕',description:'Canecas personalizadas para café, chopp, presente e setup gamer.'},
  {id:'camisetas',name:'Camisetas',slug:'camisetas',icon:'👕',description:'Camisetas geek, anime, gamer e artes enviadas pelo cliente.'},
  {id:'quadros',name:'Quadros',slug:'quadros',icon:'🖼️',description:'Quadros personalizados para decorar, presentear e eternizar momentos.'},
  {id:'copos',name:'Copos',slug:'copos',icon:'🥤',description:'Copos e brindes para festas, eventos, equipes e lembranças.'},
  {id:'geek',name:'Geek & Otaku',slug:'geek-otaku',icon:'⚔️',description:'Itens para fãs de anime, jogos, RPG e cultura pop.'},
  {id:'gamer',name:'Gamer',slug:'gamer',icon:'🎮',description:'Presentes e peças para setup, gameplay e café de jogador.'},
  {id:'casal',name:'Casal',slug:'casal',icon:'💘',description:'Presentes personalizados para datas especiais e memórias afetivas.'},
  {id:'corporativo',name:'Corporativo',slug:'corporativo',icon:'🏢',description:'Brindes para empresas, eventos, equipes e campanhas.'},
  {id:'sob-encomenda',name:'Sob encomenda',slug:'sob-encomenda',icon:'🛠️',description:'Itens criados a partir da ideia, referência ou arte do cliente.'}
];
const productsFallback = [
 {id:'p1',name:'Caneca Gamer Player 1',slug:'caneca-gamer-player-1',category_id:'canecas',price:45,image_url:'assets/caneca-player.png',gallery:['assets/caneca-player.png','assets/caneca-anime.png'],rarity:'Raro',item_type:'Caneca personalizada',material:'Cerâmica / vidro jateado',short_description:'Caneca gamer para transformar café em energia de gameplay.',description:'Uma caneca personalizada com estética gamer, ideal para presente criativo, setup ou coleção. Pode receber nome, frase, referência de jogo e arte sob encomenda.',tags:['gamer','presente','caneca'],is_featured:true,is_legendary:false,is_customizable:true,is_made_to_order:false,has_shopee:true,shopee_url:'https://shopee.com.br/',stock:6,delivery_note:'Entrega local ou Shopee',featured_rank:8},
 {id:'p2',name:'Caneca Anime Máscaras',slug:'caneca-anime-mascaras',category_id:'geek',price:49,image_url:'assets/caneca-anime.png',gallery:['assets/caneca-anime.png','assets/caneca-cafe.png'],rarity:'Épico',item_type:'Caneca otaku',material:'Cerâmica personalizada',short_description:'Arte inspirada no universo otaku para fãs e colecionadores.',description:'Caneca com visual de anime e acabamento de destaque. Uma peça forjável para quem quer presentear um fã ou criar um item do próprio inventário geek.',tags:['anime','otaku','personalizada'],is_featured:true,is_legendary:true,is_customizable:true,is_made_to_order:false,has_shopee:true,shopee_url:'https://shopee.com.br/',stock:4,delivery_note:'Entrega local ou Shopee',featured_rank:10},
 {id:'p3',name:'Quadro Casal Personalizado',slug:'quadro-casal-personalizado',category_id:'quadros',price:75,image_url:'assets/quadro-casal.png',gallery:['assets/quadro-casal.png','assets/namorados-caneca.png'],rarity:'Lendário',item_type:'Quadro personalizado',material:'Moldura + arte personalizada',short_description:'Transforme uma memória em item único de decoração.',description:'Quadro personalizado para casal, datas especiais e presentes afetivos. Ideal para eternizar momentos com uma arte personalizada e visual marcante.',tags:['casal','presente','romântico'],is_featured:true,is_legendary:false,is_customizable:true,is_made_to_order:true,has_shopee:false,shopee_url:'',stock:0,delivery_note:'Sob encomenda em Timon/Teresina',featured_rank:7},
 {id:'p4',name:'Camiseta Anime Custom',slug:'camiseta-anime-custom',category_id:'camisetas',price:45,image_url:'assets/camisa-black.png',gallery:['assets/camisa-black.png'],rarity:'Raro',item_type:'Camiseta personalizada',material:'Malha personalizada',short_description:'Camiseta com estampa geek, anime ou arte enviada pelo cliente.',description:'Camiseta personalizável para anime, games, personagens, frases, times, eventos e presentes. A arte pode ser combinada pelo WhatsApp.',tags:['camiseta','anime','geek'],is_featured:true,is_legendary:false,is_customizable:true,is_made_to_order:false,has_shopee:true,shopee_url:'https://shopee.com.br/',stock:8,delivery_note:'Entrega local ou Shopee',featured_rank:6},
 {id:'p5',name:'Copo de Guilda Personalizado',slug:'copo-de-guilda-personalizado',category_id:'copos',price:32,image_url:'assets/caneca-cafe.png',gallery:['assets/caneca-cafe.png','assets/caneca-player.png'],rarity:'Incomum',item_type:'Copo / brinde personalizado',material:'Copo personalizado',short_description:'Copo para festas, equipes, guildas, eventos e brindes criativos.',description:'Ideal para festas, eventos, empresas, equipes e encontros especiais. Pode receber nome, frase, logo, tema ou arte personalizada.',tags:['copo','brinde','evento'],is_featured:false,is_legendary:false,is_customizable:true,is_made_to_order:true,has_shopee:false,shopee_url:'',stock:0,delivery_note:'Prazo combinado no WhatsApp',featured_rank:2},
 {id:'p6',name:'Quadro de Alumínio Forjado',slug:'quadro-de-aluminio-forjado',category_id:'quadros',price:68,image_url:'assets/quadro-aluminio.png',gallery:['assets/quadro-aluminio.png'],rarity:'Épico',item_type:'Quadro de alumínio',material:'Alumínio personalizado',short_description:'Decoração personalizada com impacto visual e acabamento moderno.',description:'Quadro de alumínio personalizado para transformar paredes, quartos, lojas, setups e ambientes criativos em espaços com identidade própria.',tags:['quadro','presente','decoracao'],is_featured:false,is_legendary:false,is_customizable:true,is_made_to_order:true,has_shopee:false,shopee_url:'',stock:0,delivery_note:'Sob encomenda',featured_rank:3},
 {id:'p7',name:'Caneca Namorados Quest',slug:'caneca-namorados-quest',category_id:'casal',price:55,image_url:'assets/namorados-caneca.png',gallery:['assets/namorados-caneca.png','assets/quadro-casal.png'],rarity:'Épico',item_type:'Presente personalizado',material:'Caneca cerâmica',short_description:'Presente romântico com arte personalizada para casal.',description:'Uma peça afetiva para datas especiais, com tema, nomes, foto ou arte do casal. Ideal para transformar lembrança em item de coleção.',tags:['casal','presente','romantico'],is_featured:true,is_legendary:false,is_customizable:true,is_made_to_order:true,has_shopee:false,shopee_url:'',stock:0,delivery_note:'Sob encomenda pelo WhatsApp',featured_rank:5}
];
function money(v){return v?Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'Sob orçamento'}
function normalize(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function catName(p,cats){return (cats||categoriesFallback).find(c=>c.id===p.category_id)?.name || 'Item'}
function rarityClass(r){const x=normalize(r); if(x.includes('lend'))return 'legendary'; if(x.includes('ep'))return 'epic'; if(x.includes('rar'))return 'rare'; return ''}
function productUrl(p){return `produto.html?slug=${encodeURIComponent(p.slug||p.id)}`}
function waLink(p){const msg = encodeURIComponent(`Olá! Tenho interesse em forjar este item: ${p.name}. Gostaria de saber valores, personalização e prazo.${location?.origin && location.origin !== 'null' ? ` Link: ${location.origin}/${productUrl(p)}` : ''}`); return `https://wa.me/${WHATSAPP_NUMBER}?text=${msg}`}
async function loadStoreData(){
  if(db){
    try{
      const [{data:cats,error:ce},{data:prods,error:pe}] = await Promise.all([
        db.from('categories').select('*').eq('is_active',true).order('name'),
        db.from('products').select('*').eq('is_active',true).order('featured_rank',{ascending:false}).order('created_at',{ascending:false})
      ]);
      return {categories:(!ce&&cats?.length)?cats:categoriesFallback,products:(!pe&&prods?.length)?prods.map(p=>({...p,gallery:Array.isArray(p.gallery)?p.gallery:[],tags:Array.isArray(p.tags)?p.tags:[]})):productsFallback};
    }catch(e){}
  }
  return {categories:categoriesFallback,products:productsFallback};
}
