import canecaAnime from '../assets/caneca-anime.png'
import canecaPlayer from '../assets/caneca-player.png'
import camisaBlack from '../assets/camisa-black.png'
import quadroCasal from '../assets/quadro-casal.png'
import canecaCafe from '../assets/caneca-cafe.png'
import quadroAluminio from '../assets/quadro-aluminio.png'
import namoradosCaneca from '../assets/namorados-caneca.png'

export const fallbackCategories = [
  { id: 'cat-canecas', name: 'Canecas', slug: 'canecas', icon: '☕', description: 'Canecas personalizadas para café, chopp e presentes criativos.', is_active: true },
  { id: 'cat-camisetas', name: 'Camisetas', slug: 'camisetas', icon: '👕', description: 'Estampas geek, anime, gamer e artes enviadas pelo cliente.', is_active: true },
  { id: 'cat-quadros', name: 'Quadros', slug: 'quadros', icon: '🖼️', description: 'Quadros personalizados para decoração e presentes especiais.', is_active: true },
  { id: 'cat-copos', name: 'Copos e brindes', slug: 'copos-e-brindes', icon: '🥤', description: 'Itens para eventos, empresas, aniversários e encontros.', is_active: true },
  { id: 'cat-geek', name: 'Geek & Otaku', slug: 'geek-otaku', icon: '⚔️', description: 'Produtos para quem vive anime, games, RPG e cultura pop.', is_active: true },
  { id: 'cat-casal', name: 'Presentes românticos', slug: 'presentes-romanticos', icon: '💘', description: 'Peças únicas para eternizar momentos a dois.', is_active: true },
]

export const fallbackProducts = [
  { id: 'p1', name: 'Caneca Gamer Player 1', slug: 'caneca-gamer-player-1', short_description: 'Caneca personalizada para transformar café em energia de gameplay.', description: 'Uma caneca gamer personalizável para presente, uso diário ou setup. Ideal para quem gosta de produtos com personalidade e visual geek.', category_id: 'cat-canecas', category: fallbackCategories[0], price: 45, image_url: canecaPlayer, gallery: [canecaPlayer], shopee_url: '#', is_active: true, is_featured: true, is_legendary: false, is_customizable: true, is_made_to_order: false, has_shopee: true, stock: 8, tags: ['gamer', 'presente', 'caneca'], rarity: 'Raro', item_type: 'Caneca personalizada', material: 'Cerâmica', delivery_note: 'Entrega local combinada em Timon e Teresina.' },
  { id: 'p2', name: 'Caneca Anime Máscaras', slug: 'caneca-anime-mascaras', short_description: 'Arte inspirada no universo otaku, com visual de item épico.', description: 'Produto personalizável para fãs de anime, colecionadores e presentes criativos. Pode receber nome, frase ou referência enviada pelo cliente.', category_id: 'cat-geek', category: fallbackCategories[4], price: 49, image_url: canecaAnime, gallery: [canecaAnime], shopee_url: '#', is_active: true, is_featured: true, is_legendary: false, is_customizable: true, is_made_to_order: false, has_shopee: true, stock: 5, tags: ['anime', 'otaku', 'personalizada'], rarity: 'Épico', item_type: 'Caneca personalizada', material: 'Cerâmica', delivery_note: 'Compra pela Shopee quando disponível.' },
  { id: 'p3', name: 'Quadro Casal Personalizado', slug: 'quadro-casal-personalizado', short_description: 'Uma memória transformada em peça decorativa única.', description: 'Quadro sob encomenda para casais, datas especiais e presentes com valor emocional. A arte é combinada no atendimento antes da produção.', category_id: 'cat-quadros', category: fallbackCategories[2], price: null, image_url: quadroCasal, gallery: [quadroCasal], shopee_url: '', is_active: true, is_featured: true, is_legendary: true, is_customizable: true, is_made_to_order: true, has_shopee: false, stock: 0, tags: ['casal', 'romântico', 'presente'], rarity: 'Lendário', item_type: 'Quadro personalizado', material: 'Moldura + impressão personalizada', delivery_note: 'Sob orçamento via WhatsApp.' },
  { id: 'p4', name: 'Camiseta Anime Custom', slug: 'camiseta-anime-custom', short_description: 'Camiseta com estampa geek, anime ou arte enviada pelo cliente.', description: 'Camiseta personalizada para eventos, fãs de anime e presentes criativos. Pode ser criada com tema, frase, personagem ou arte própria.', category_id: 'cat-camisetas', category: fallbackCategories[1], price: 45, image_url: camisaBlack, gallery: [camisaBlack], shopee_url: '#', is_active: true, is_featured: true, is_legendary: false, is_customizable: true, is_made_to_order: false, has_shopee: true, stock: 12, tags: ['camiseta', 'anime', 'geek'], rarity: 'Raro', item_type: 'Camiseta personalizada', material: 'Malha personalizada', delivery_note: 'Disponibilidade conforme tamanho e arte.' },
  { id: 'p5', name: 'Caneca Café de Aventura', slug: 'caneca-cafe-de-aventura', short_description: 'Caneca temática para quem começa o dia como protagonista.', description: 'Caneca personalizada com tema de café, frases e arte enviada pelo cliente. Boa opção para presente rápido.', category_id: 'cat-canecas', category: fallbackCategories[0], price: 45, image_url: canecaCafe, gallery: [canecaCafe], shopee_url: '', is_active: true, is_featured: false, is_legendary: false, is_customizable: true, is_made_to_order: true, has_shopee: false, stock: 0, tags: ['café', 'caneca', 'presente'], rarity: 'Incomum', item_type: 'Caneca personalizada', material: 'Cerâmica', delivery_note: 'Produção sob encomenda.' },
  { id: 'p6', name: 'Quadro de Alumínio Custom', slug: 'quadro-de-aluminio-custom', short_description: 'Quadro personalizado para tornar qualquer lugar especial.', description: 'Quadro em alumínio com arte personalizada para decoração, presentes e ambientes comerciais.', category_id: 'cat-quadros', category: fallbackCategories[2], price: null, image_url: quadroAluminio, gallery: [quadroAluminio], shopee_url: '', is_active: true, is_featured: false, is_legendary: false, is_customizable: true, is_made_to_order: true, has_shopee: false, stock: 0, tags: ['quadro', 'decoração', 'personalizado'], rarity: 'Épico', item_type: 'Quadro personalizado', material: 'Alumínio', delivery_note: 'Prazo combinado pelo WhatsApp.' },
  { id: 'p7', name: 'Caneca Namorados', slug: 'caneca-namorados', short_description: 'Presente romântico com arte personalizada para casal.', description: 'Caneca personalizada para datas especiais, Dia dos Namorados e presentes sob medida.', category_id: 'cat-casal', category: fallbackCategories[5], price: 45, image_url: namoradosCaneca, gallery: [namoradosCaneca], shopee_url: '', is_active: true, is_featured: false, is_legendary: false, is_customizable: true, is_made_to_order: true, has_shopee: false, stock: 0, tags: ['casal', 'romântico', 'caneca'], rarity: 'Raro', item_type: 'Caneca personalizada', material: 'Cerâmica', delivery_note: 'Personalização combinada antes da produção.' },
]
